using SafeTrace.Application.DTOs.FacebookPosts.Response;

namespace SafeTrace.Application.Mapping
{
    public class FacebookImportedPostMappingProfile : Profile
    {
        public FacebookImportedPostMappingProfile()
        {
            CreateMap<SocialPostAiResultDto, FacebookImportedPost>()
                .ForMember(dest => dest.Classification, opt => opt.MapFrom(src => src.Classification))
                .ForMember(dest => dest.Confidence, opt => opt.MapFrom(src => src.Confidence))
                .ForMember(dest => dest.FName, opt => opt.MapFrom(src => src.Person.FirstName))
                .ForMember(dest => dest.SName, opt => opt.MapFrom(src => src.Person.SecondName))
                .ForMember(dest => dest.TName, opt => opt.MapFrom(src => src.Person.ThirdName))
                .ForMember(dest => dest.LName, opt => opt.MapFrom(src => src.Person.LastName))
                .ForMember(dest => dest.Gender, opt => opt.MapFrom(src => src.Person.Gender))
                .ForMember(dest => dest.Age, opt => opt.MapFrom(src => src.Person.Age))
                .ForMember(dest => dest.Government, opt => opt.MapFrom(src => src.MissingInfo.Government))
                .ForMember(dest => dest.City, opt => opt.MapFrom(src => src.MissingInfo.City))
                .ForMember(dest => dest.Street, opt => opt.MapFrom(src => src.MissingInfo.Street))
                .ForMember(dest => dest.EventDate, opt => opt.MapFrom(src => src.MissingInfo.EventDate))
                .ForMember(dest => dest.CommunicationPhone, opt => opt.MapFrom(src => src.Contact.Phone))
                .ForMember(dest => dest.Description, opt => opt.MapFrom(src => src.Description))
                .ForMember(dest => dest.Relation, opt => opt.MapFrom(src => src.Relation))
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookPageId, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookPage, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookPostId, opt => opt.Ignore())
                .ForMember(dest => dest.PostText, opt => opt.Ignore())
                .ForMember(dest => dest.PostUrl, opt => opt.Ignore())
                .ForMember(dest => dest.PublishedAt, opt => opt.Ignore())
                .ForMember(dest => dest.Latitude, opt => opt.Ignore())
                .ForMember(dest => dest.Longitude, opt => opt.Ignore())
                .ForMember(dest => dest.Status, opt => opt.Ignore())
                .ForMember(dest => dest.CaseId, opt => opt.Ignore())
                .ForMember(dest => dest.Case, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.AnalyzedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.RowVersion, opt => opt.Ignore())
                .ForMember(dest => dest.Files, opt => opt.Ignore());

            CreateMap<FacebookPostMediaDto, FacebookImportedPostFile>()
                .ForMember(dest => dest.FileUrl, opt => opt.MapFrom(src => src.FileUrl.Trim()))
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookImportedPostId, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookImportedPost, opt => opt.Ignore());

            CreateMap<FacebookPostDto, FacebookImportedPost>()
                .ForMember(dest => dest.FacebookPostId, opt => opt.MapFrom(src => src.FacebookPostId))
                .ForMember(dest => dest.PostText, opt => opt.MapFrom(src => string.IsNullOrWhiteSpace(src.PostText) ? null : src.PostText.Trim()))
                .ForMember(dest => dest.PostUrl, opt => opt.MapFrom(src => string.IsNullOrWhiteSpace(src.PostUrl) ? null : src.PostUrl.Trim()))
                .ForMember(dest => dest.PublishedAt, opt => opt.MapFrom(src => src.PublishedAt))
                .ForMember(dest => dest.Status, opt => opt.MapFrom(_ => FacebookImportedPostStatus.PendingAnalysis))
                .ForMember(dest => dest.Files, opt => opt.MapFrom(src => src.Media.Where(media => !string.IsNullOrWhiteSpace(media.FileUrl)).DistinctBy(media => media.FileUrl, StringComparer.Ordinal)))
                .ForMember(dest => dest.Id, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookPageId, opt => opt.Ignore())
                .ForMember(dest => dest.FacebookPage, opt => opt.Ignore())
                .ForMember(dest => dest.Classification, opt => opt.Ignore())
                .ForMember(dest => dest.Confidence, opt => opt.Ignore())
                .ForMember(dest => dest.FName, opt => opt.Ignore())
                .ForMember(dest => dest.SName, opt => opt.Ignore())
                .ForMember(dest => dest.TName, opt => opt.Ignore())
                .ForMember(dest => dest.LName, opt => opt.Ignore())
                .ForMember(dest => dest.Gender, opt => opt.Ignore())
                .ForMember(dest => dest.Age, opt => opt.Ignore())
                .ForMember(dest => dest.Government, opt => opt.Ignore())
                .ForMember(dest => dest.City, opt => opt.Ignore())
                .ForMember(dest => dest.Street, opt => opt.Ignore())
                .ForMember(dest => dest.EventDate, opt => opt.Ignore())
                .ForMember(dest => dest.CommunicationPhone, opt => opt.Ignore())
                .ForMember(dest => dest.Description, opt => opt.Ignore())
                .ForMember(dest => dest.Relation, opt => opt.Ignore())
                .ForMember(dest => dest.Latitude, opt => opt.Ignore())
                .ForMember(dest => dest.Longitude, opt => opt.Ignore())
                .ForMember(dest => dest.CaseId, opt => opt.Ignore())
                .ForMember(dest => dest.Case, opt => opt.Ignore())
                .ForMember(dest => dest.CreatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.AnalyzedAt, opt => opt.Ignore())
                .ForMember(dest => dest.UpdatedAt, opt => opt.Ignore())
                .ForMember(dest => dest.RowVersion, opt => opt.Ignore());
        }
    }
}
