<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Licenses\**" />
		<Compile Remove="Service\**" />
		<EmbeddedResource Remove="Licenses\**" />
		<EmbeddedResource Remove="Service\**" />
		<None Remove="Licenses\**" />
		<None Remove="Service\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.4.11" />
		<PackageReference Include="AWSSDK.Rekognition" Version="4.0.4.8" />
		<PackageReference Include="ElmahCore" Version="2.1.2" />
		<PackageReference Include="ElmahCore.Sql" Version="2.1.2" />
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SixLabors.ImageSharp" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SafeTrace.Application\SafeTrace.Application.csproj" />
		<ProjectReference Include="..\SafeTrace.Domain\SafeTrace.Domain.csproj" />
	</ItemGroup>

</Project>
